version: '3.8'

services:
  db:
    image: postgres:15
    container_name: imagehosting_postgres_users
    environment:
      POSTGRES_USER: LOGIN
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: imagehosting_users
    ports:
      - "4432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
