version: '3.8'

services:
  db:
    image: postgres:15
    container_name: imagehosting_postgres_galery
    environment:
      POSTGRES_USER: imagehosting_galery_admin
      POSTGRES_PASSWORD: imagehosting_8921
      POSTGRES_DB: imagehosting_galery
    ports:
      - "4433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: